== Journal, Monday, June 24, 2024
//Settings:
:icons: font
:bibtex-style: harvard-gesellschaft-fur-bildung-und-forschung-in-europa
:toc:

=== Notes
* https://www.youtube.com/watch?v=-578C3gFepU&list=TLPQMjQwNjIwMjRENwmMk9putg&index=3[Do I actually need to "figure out exactly"] each camera ankle for my goal of making xref:concept/VisualNovel.adoc[VN]s?
* learning about differences and similarities between https://youtu.be/RyxtZnWCUSM?si=OaIl9H-OtG5yxDgh[lesbian and straight women]
** I start to think more and more that the word "man" does not refer to the people with a penis but to a certain expectation of behavioural patterns that we don't like.
   And I say "we" because men, i.e. people with a penis, also don't like these behaviours in their partners.
** Listening to this is extremely stressful for me. I feel almost identical to the participants, but I know that in their mind, I'm behind this label of "man", and therefore on the outside.
   Not included, having to proof my worth, my trustability, my belonging. It's hard to face both at the same time: Seeing the people who you feel you belong to, but who feel the opposite about you,
   because of attributes you can't change without significant consequences.
