== Journal, Tuesday, June 11, 2024
//Settings:
:icons: font
:bibtex-style: harvard-gesellschaft-fur-bildung-und-forschung-in-europa
:toc:

=== Quick and Dirty Review: Teachino

Ein nettes Content Management Tool für Lehrer, mit überraschendem Fokus auf den Lehrer als zahlenden Kunden.
Ich glaube an das Team und würde die Software selber benutzen, aber nicht wegen dem KI Feature.
Ich hoffe, das Entwicklerteam von Teachino findet einen Partner der Ahnung von https://github.com/fallbackerik/secondbrain.py/blob/main/concept/Business2Administration.adoc[Verwaltungskunden] hat.

=== Notes
Hab über https://bildung.social/@m_drabe/112598053713184910[dieses neue KI basierte Tool für Lehrer] erfahren und verschaffe mir mit Youtube einen schnellen Überblick, ob ich mir das Geben würde.

Dazu geb ich erst mal bei Youtube den Namen ein, scrolle runter und clicke bei Videos die interessant aussehen auf https://youtu.be/N-HpmruO5UM?si=PqRa1FtHy6Uun4Uw[`[Add to Queue\]`]. Dann gucke ich die Queue durch.

Erst mal https://youtu.be/EibTD_H2NkM?si=Q0y-z4vL_59KuVXD[eine kurze Übersicht von den Entwicklern selbst].
Erst mal sieht es aus, wie ein Content Management System für Lehrer. Interessanterweise scheint der Lehrer als Individuum das Ziel zu sein, nicht die Schule oder das Amt.
Ein Blick https://www.teachino.io/preise[auf die Pricing Seite] bestätigt, dass auch die Finanzierung über den Lehrer selbst laufen soll.
Das ist für die Firma eigentlich nicht gut. Sie hätten schon lieber Kontingente aus Lehrern und Schulen.
Aber es könnte so schwer sein, da dann an Finanzierung zu kommen... unklar.

Das Nutzerinterface sieht gut aus.

In https://youtu.be/xwlDuXtUV-g?si=eYth3SoiRurQBZXO[einem zweiten Video] geht es um die Zusammenarbeit zwischen mehreren Lehrern, also Sharing und Syncing von Content. Gutes Feature.
Ohne sync mit richtigem Git drunter bin ich mir aber immer nicht sicher in wie weit das dann irgendwann chaotisch wird.

Überrascht war ich, dass ich jetzt extra noch mal suchen musste, https://youtu.be/MCclpMqMEqk?si=jtaE0Kr-wDfVlXdI[wo die KI herkommt].
Richtig toll, dass die Entwickler selbst auch andere KIs vorstellen und empfehlen.

Die eigene KI scheint hauptsächlich ein "Weiterschreiben" Feature zu beinhalten. Also ein kontext-basierter Text Generator, der den kreativen Prozess des Lehrers unterstützt.
Aus eigener Erfahrung it Grammarly AI kann ich sagen, dass es hilft, aber auf keinen Fall die ganze Arbeit abnimmt.
Da ist die KI gutes Feature, aber sicher kein Alleinstellungsmerkmal oder sollte gar der Grund sein, die Software zu kaufen.

Trotzdem haben mich die Videos überzeugt. Ich mag besonders das Entwickler Team, ihr Fokus auf den Lehrer als Hauptnutzer, ihre Oberflächen Gestaltung (UX) und die Idee Lern Content als Marketing Content zu nutzen.
