= Daily Journal Wednesday, Jun 12, 2024
//Settings:
:icons: font
:bibtex-style: harvard-gesellschaft-fur-bildung-und-forschung-in-europa
:toc:

== How to Learn Languages in 2024 - 1 By Comprehension
===  Summary

While watching the Youtube recommendation about how to https://www.youtube.com/watch?v=9Olt2FO99SQ["(...) REALLY Learn Languages"],
I'll take some notes and this here is the summary.


=== Ongoing Notes

* https://www.youtube.com/@matt_brooks-green[Matt Brooks-Green] interviews http://backseatlinguist.com/blog/[Dr Jeff McQuilla] about McQuilla's science (or his understanding of current science status-quo; TODO)
* McQuillan is a student of Dr Stephen Krashen
* <<Learning>> vs <<Acquisition>>
+
[cols="1,1"]
|===
|Learning |Acquisition 

| conscious
| subconscious

| ???
| ???

| traditional focus
| more useful (why?)

|===

* subconscious knowledge comes from understanding messages that are <<comprehensible>>
* shows an example, where he teaches "these are two hands" in Spanish, just by showing what he says with his hands
* recommends: look for a teacher that works visually, speaks slowly, speaks clearly (!TODO for my English?), 
* recommends https://youtu.be/SFZyArZa-o0?si=m3CYf-By9x5NaXtI[Beniko Mason] as an examplary teacher
* How does <<grammar>> fit into this?
* One part of grammar that is often highlighted is <<syntax>>, the order of words in a sentence
* Also, grammar is often seen as a way of teaching language
* McQuilla has grammar rule books in his mind, when he thinks about it;
  personally, I believe that grammar exercise books are helpful at a certain stage and that mid-level students who want to become fluent need to focus on grammar exercises
  (talking about myself here as well)
* applying grammar rules is not something we would do in real life, as when we communicate we focus on transmitting meaning
* **also: the brain cannot do meaning-construction and grammar-construction at the same time** (TODO: scientific reference)
** Most students make the same mistakes with or without grammar lessons before the writing exercise (TODO: scientific evidence?)
*** side note: What about pre-tests? If you pretest and then feed grammar lessons based on the mistakes of the student, they might drastically improve learning? pre-testing is scientifically proven to work (TODO: reference)
*** at 18:50 again, McQuillan claims grammar lessons and single-vocab study doesn't help at all and that there's research backing his understanding
*** later he corrects it a little: it is possible, but the time-efficiency is very low and the time is better spent with other exercises
*** Matt adds, that learning through comprehending stories is also **MORE FUN** (no further scientific evidence needed!)
* McQuilla says, because it's hard to measure acquisition status (<<output metric>>), it's important to measure understanding-percentage (<<input metric>>)
* therefore, improve amount of comprehensible content you can get (independent of your level of learning? what about <<diminishing returns>>?)
* in the video description there is a suggestion for this https://learn.storylearning.com/uncovered-select-language37129904?affiliate_id=4012887[story based language learning site]
* <<vocabulary acquisition>> is done subconsciously and incrementally
** you try to comprehend and by that learn new words
** usually you pick up a detail, interpretation or a sense of the new word
** each time you see it in a new context you pick up new meaning
** at some point it is acquired and usable
** by focussing on comprehension, you automatically sort and filter based on the words you meet more often; personal note: this feels risky, maybe teachers could help the right texts to read

== How to Learn Languages in 2024 - 2 By Stories

The previous video (TODO how to reference that in asciidoc) recommmended https://youtu.be/oQ74fe2fMDk?si=sMglOKdgmebHg5Ph[this teacher], so I'll check out her ideas.
It needs a teacher who understands story presentation and grammar very well. Then the student can focus on story comprehension in the target language during guided exercise, and read stories by themselves
in their sparetime. Mason made primary science herself to ensure her method works and is open for feedback from her peers.

* method is called <<story listening>> and <<guided self-selected reading>> (SL/GSSR)
* assumption: focused listening/reading comprehension might be more efficient than immersion. (TODO: science refs)
* assumption: input > input+output (Mason, 2011) (Mason, Krashen, 2019)
* implicetely Mason says, that the teacher is the person who needs to be fluent in the grammar rules, so they can create and choose content appropriately for the students and understand the student's current status

== Notes to Self, Brainfarts, etc

* am i prefering urban to garden environments because of the visual info-to-noise ratio?
* asciidoc:
** Shouldn't I be able to tell the parser: here's a folder with `adoc` files. When building cross references, check all the files, and build links towards all the generated files
** is that the thing that is missing to build wikis with Asciidoc?
* TODO: https://www.youtube.com/watch?v=wOXxs2YpJCk&list=TLPQMTIwNjIwMjRVXsTIKVEsoA&index=3[New Japanese Exercise]
* inspired by https://youtu.be/iio_ZOS2T3s?si=izHOv2B1NF4Efcvr[this video recommendation] from Youtube:
** Why have the older Zeldas be more fun to me, although the Switch Zeldas have much better graphics, are more mobile, and have the logically better world interaction?
*** I think it's because of the interaction with NPCs. Usually non-interactiveness with intelligent being is what I miss the most
*** In older versions most interactions where fighting NPCs, though
*** I don't like fighting
*** **New idea**: Why not let the main character dance with the NPCs? It's a similar interactive, physical way of communication; the UI/UX could be almost the same, and it's completely non-violent
** Side note: The first in-game engine I know that allowed players and game makers to make movies was Warcraft 3
