on: [push, workflow_dispatch]

jobs:
  generate_html_job:
    runs-on: ubuntu-latest
    name: Generate HTML
    steps:
      - uses: actions/checkout@v4
      - name: list filesystem
        run: ls -al
      - name: do sth with python
        run: python --version
      - name: venv
        run: python -m venv venv
      - name: activate venv
        run: source venv/bin/activate
      - name: install dependencies
        run: pip install -r requirements.txt
