on: [push, workflow_dispatch]

jobs:
  generate_html_job:
    runs-on: ubuntu-latest
    name: Generate HTML
    steps:
      - uses: actions/checkout@v4
      - name: list filesystem
        run: ls -al
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: generate html
        run: asciidoc --verbose -o web/index.html README.adoc
      - name: list filesystem
        run: ls -al
      - name: upload html
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web'
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
