on: [push, workflow_dispatch]

jobs:
  generate_html_job:
    runs-on: ubuntu-latest
    name: Generate HTML
    steps:
      - uses: actions/checkout@v4
      - name: list filesystem
        run: ls -al
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: generate html
        run: asciidoc --verbose -o README.html README.adoc
      - name: list filesystem
        run: ls -al
