on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  generate_html_job:
    runs-on: ubuntu-latest
    name: Generate HTML
    steps:
      - uses: actions/checkout@v4
      - name: list filesystem
        run: ls -al
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: preprocess adoc files
        run: python generate_includes.py
      - name: what's in the index.adoc after?
        run: cat index.adoc
      - name: pwd
        run: pwd
      - name: find asciidoc code
        run: which asciidoc
      - name: cat asciidoc
        run: cat /home/runner/.local/bin/asciidoc
      - name: generate html
        run: python ./call_asciidoc.py --verbose -o web/index.html index.adoc || echo "failed"
      - name: list filesystem
        run: ls -al
      - name: list web filesystem
        run: ls -al web
      - name: upload html
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web'
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
