on: [push, workflow_dispatch]

jobs:
  generate_html_job:
    runs-on: ubuntu-latest
    name: Generate HTML
    steps:
      - uses: actions/checkout@v4
      - name: list filesystem
        run: ls -al
      - name: do sth with python
        run: python --version
      - name: venv
        run: python -m venv venv
      - name: activate venv
        run: source venv/bin/activate && pip install -U pip
      - name: install dependencies
        run: source venv/bin/activate && pip install -r requirements.txt
      - name: testing whether each run is actually inside the venv
        run: source venv/bin/activate && pip freeze
      - name: generate html
        run: source venv/bin/activate && asciidoc3 -n -a icons -a toc -o test.html test.txt
