on: [push, workflow_dispatch]

jobs:
  generate_html_job:
    runs-on: ubuntu-latest
    name: Generate HTML
    steps:
      - uses: actions/checkout@v4
      - name: list filesystem
        run: ls -al output/
      - name: do sth with python
        run: python
