on: [workflow_dispatch]

permissions:
  contents: write
  id-token: write

jobs:
  create_daily_journal_file_job:
    runs-on: ubuntu-latest
    name: Generate Daily Journal File from Template
    steps:
    
      - uses: actions/checkout@v4

      - name: create file
        run: python tools/new_daily.py

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Create Daily Journal file from template'
          add: 'journal/'
